set-option -g default-command zsh

set-option -g renumber-windows on

set-option -g allow-passthrough on

set-option -g status-justify left
set-option -g status-right "#{b:pane_current_path} | #(ipconfig getifaddr en0) "

# Enable Mouse
setw -g mouse on

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind y split-window -h -c "#{pane_current_path}" "opencode"
bind m last-window

# Vim motions for up and down
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


bind r run-shell ' \
  width=$(tmux display -p "#{window_width}"); \
  size=$((width * 30 / 100)); \
  tmux split-window -h -l $size -c "#{pane_current_path}/legacy/PioneerRx.Mobile.Apps" \
'

bind R split-window -h -c "#{pane_current_path}/legacy/PioneerRx.Mobile.Apps"
